### ISSUE TITLE
Match Stoneblock2 version on FTBApp with Curseforge

### ISSUE THREAD

**Issue by Shybella** [tfox83/fubarpack#3]
Can you match the version of Stoneblock2 on FTBApp onto Curseforge?

Curseforge is running 1.16.1 while FTBApp is running 1.21.1 

Thank you not sure if this is the right place to get ahold of you, all the other FTB Packs match and they were updated at the same time.

**Comment by tfox83** [comment]
I know longer work for FTB, why don’t you report your issue on their GitHub.
